### ISSUE TITLE
How do I change the color of an icon?

### ISSUE THREAD

**Issue by attaradev** [useAnimations/react-useanimations#1]

**Comment by ndom91** [comment]
Any word on if this is possible? I've tried manually changing the fill color on every element up and down the tree of your component and unfortunately it had no effect.

**Comment by tuanphungcz** [comment]
To support color editing, we will have to edit the SVG itself, but this is already in our roadmap.

**Comment by ndom91** [comment]
Found a little work-around:

i.e. you have the parent button with a class 'export-btn', you can set the following CSS:

```css
.export-btn path {
  stroke: #fff
}
```

Which will change every single `path` below `.export-btn` in the DOM tree to white.
