### ISSUE TITLE
Typescript and hooks

### ISSUE THREAD

**Issue by tuanphungcz** [useAnimations/react-useanimations#12]
Lets rewrite to typescript and hooks, let me know if anyone is interested in contributing 👍

**Comment by tuanphungcz** [comment]
cc @zilahir @tsujp

**Comment by zilahir** [comment]
let's create a branch for it?

**Comment by tuanphungcz** [comment]
yep sure, would you take the TS part or the hook part (or you can even both :D)

**Comment by tsujp** [comment]
Keen. A bit busy for the next 2 weeks but I'll dip in if and when I can until then at which time I will begin taking a proper look.

**Comment by marekfeikus** [comment]
Done
