### ISSUE TITLE
Toggle Icon State

### ISSUE THREAD

**Issue by samturner3** [useAnimations/react-useanimations#13]
Is there a way to toggle the state of the animation (between state 1 and 2 ie. hamburger menu from 3 lines to X icon) programmatically?

```
const [mobileNavMenuIsOpen, setMobileNavMenuIsOpen] = useState(false)
```
I have above code and want to tie the animation state to `mobileNavMenuIsOpen`.
The user may close nav menu by clicking off or swiping it closed. I need the icon to reflect the state.

**Comment by marekfeikus** [comment]
@samturner3 Yop, use the new `reverse` prop. Check the new README.
