### ISSUE TITLE
[Feature Request] Reduce bundle size, performance improvements

### ISSUE THREAD

**Issue by pixelmord** [useAnimations/react-useanimations#19]
## First of all: Great animations, thank you!

However, having said that ^^ I noticed that the bundle size for even using only ONE icon is [568.8 KB uncompressed](https://bundlephobia.com/result?p=react-useanimations@1.2.13).
For a modern web app that is imho not tolerable without implementing a workaround by e.g. lazy loading the module. I guess I will either do that or for the time being move to another solution for my current project.

There are two factors ion the lib currently contributing to this heavy load from what I see: 
- First is lottie-web as a dep with [247.3 KB](https://bundlephobia.com/result?p=lottie-web@5.6.8), which might be unavoidable? ATM I cannot judge how feasible that would be to create animations without it.. Maybe a lighter version would help?
- Second is the fact that all the animations together contribute to about 260 KB in my bundle analysis. So here I guess is the "easiest" part to reduce the size by splitting up the components in one per animation and to make the lib tree-shakeable (Unfortunately I am no expert in how to do that, so cannot help myself :( ). 

And thinking about my initial mention of lazy loading, I could imagine having a lightweight version of the icon as SVG without animation as well could open up the way of rendering that as a "placeholder" and then lazy load the desired animated version. This mechanism could possibly also be a feature of the library.

Thanks for your consideration.

**Comment by marekfeikus** [comment]
@pixelmord  Hi man, I'm currently helping @digilifecz123 & @thesvbd  with the new major release for this lib and I've managed what you've been asking for. 
1. we will use `lottie-little` which is almost half the size
2. only those icons you will need will be loaded - API breaking change (you will import and pass them to `UseAnimations` directly without the need of `animationKey`)
3. also removed `styled-components` from the deps - using pure JS for style changes.

The last thing regarding the lazy loading. That could be the sound of the future for next releases :)

**Comment by marekfeikus** [comment]
Done
