### ISSUE TITLE
Suggest rename to not give the impression of being a hooks library.

### ISSUE THREAD

**Issue by webbertakken** [useAnimations/react-useanimations#2]
As pointed out on Reddit [here](https://www.reddit.com/r/reactjs/comments/dd7wb6/just_published_a_react_animated_icons_library/f2eoqsi?utm_source=share&utm_medium=web2x) `use-*` is associated with hooks within the react community.

Suggest naming the library differently. As you indicated you're looking for proposed name i would suggest to call the library `react-animated-icons` as it makes a lot of sense and has most upvotes on the thread.

**Comment by tuanphungcz** [comment]
yeah we were thinking about rebranding the library name. Funny thing, someone took the name already https://github.com/saaymeen/react-animated-icons :D

**Comment by webbertakken** [comment]
Oh wow. That might be the reddit user having reserved it for you though, given the creation date of that repo.

**Comment by tuanphungcz** [comment]
I would postpone renaming repo for now :)
