### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by smuralimohan** [useAnimations/react-useanimations#20]
Hi, 

Thanks for an awesome library. Appreciate it much. Wanted to ask if you could add a couple more useful icons for everyday use...
1. An animated question mark icon for dialog boxes.
2. A tick mark animation for success messages.
3. An 'x' mark animation for error messages.

Thought about (2) and (3) came to my mind after looking at SweetAlert. 
Thank you.

**Comment by thesvbd** [comment]
Hi @smuralimohan 
Thanks for the tip. I made and published the three icons now. Pretty sure that it will need more variants in future. For now are downloadable from the website only, but we will update the lib. soon.

**Comment by marekfeikus** [comment]
@thesvbd Cool, reopening for not to forget on that. Will implement when I find some spare time.

**Comment by muke1908** [comment]
> Hi @smuralimohan
> Thanks for the tip. I made and published the three icons now. Pretty sure that it will need more variants in future. For now are downloadable from the website only, but we will update the lib. soon.

Hi is there a way to use Lottie file or svg in this react library?

**Comment by marekfeikus** [comment]
@muke1908 with this lib you can only use the implemented lottie animations. If you want svg versions, you can download them from https://useanimations.com/ 

Closing as new icons are added by #44
