### ISSUE TITLE
A11y Attributes for the SVG

### ISSUE THREAD

**Issue by ghost** [useAnimations/react-useanimations#28]
Is there any way to include attributes like `tab-index` to the `svg` tag? And what about adding a `title` tag inside the `svg`? I mean, a11y features in general.

One last thing, I'm trying to implement a common keyboard navigation feature for dropdown menus. When pressing the `Esc` key:

> The menu closes. On closing, the focus is automatically repositioned onto the button that opened the menu.

[https://a11y-guidelines.orange.com/web_EN/exemples/simple-menu/simple-menu.html](https://a11y-guidelines.orange.com/web_EN/exemples/simple-menu/simple-menu.html)

In my case, a button is wrapping the svg wrapper, exactly like in the comment referenced below. The click event on the svg wrapper toggles the animation as expected, but a `keydown` on a sibling `ul` doesn't initilize the animation's reversal. Both events toggle the same state. And I am passing the changing state to the `reverse` prop. I was expecting the animation to work in the same way.

**EDIT:** I guess a possible workaround to the `tab-index` is the change presented in [#6/issuecomment-663054283](https://github.com/useAnimations/react-useanimations/issues/6#issuecomment-663054283)

**Comment by marekfeikus** [comment]
@mjfneto You cannot access the underlying svg element - as mentioned [here](https://github.com/airbnb/lottie-web/issues/1935) . But yes, you can set the attributes to the parent div, like the new `render` prop allows.
