### ISSUE TITLE
Is it possible to control animation duration?

### ISSUE THREAD

**Issue by Slurpgoose** [useAnimations/react-useanimations#29]
The docs states:
> options -	{}	 - provide any other custom options which will override the default ones

I tried passing an object options={{ animationDuration: '2s' }} but it does not seem to have any effect. 
I do not have a good understanding of SVG animations so apologize if this approach makes no sense here.

Thanks

**Comment by marekfeikus** [comment]
@Slurpgoose just these options are available 
![image](https://user-images.githubusercontent.com/4778643/89406096-d3d73380-d746-11ea-98b5-5f2fe6f043ff.png)
