### ISSUE TITLE
Rewrite using hooks

### ISSUE THREAD

**Issue by webbertakken** [useAnimations/react-useanimations#3]
Since peer dependency of react is post-hooks, the usage of hooks would make sense.

I'd be willing to send a PR if you're open for PRs

**Comment by tuanphungcz** [comment]
@webbertakken I would love to have it in hooks!

actually, at first, I wrote it in hooks. (https://github.com/useAnimations/react-useanimations/commit/b4ee44d2aad92933f373bb9e00c8b76ac970e6bd#diff-73642d587163f2eb4d72f0fa6ebfba02)

But for some reason, after I published the package I was getting this error - https://reactjs.org/warnings/invalid-hook-call-warning.html
1) React versions were the same
2) Usage of hooks seemed correct

I was able to fix it locally when using `yarn link` by 

```
This problem can also come up when you use npm link or an equivalent. 
In that case, your bundler might “see” two Reacts — one in application folder
 and one in your library folder. Assuming myapp and mylib are sibling folders,
 one possible fix is to run npm link ../myapp/node_modules/react from mylib. 
This should make the library use the application’s React copy.
```

but I dont know how to fix in when the package is published.

**Comment by tsujp** [comment]
Would a community effort to rewrite this back into Hooks _and_ TypeScript be considered?

**Comment by tuanphungcz** [comment]
@webbertakken I would love to have this in TS and hooks? 😍 Are you down for it? 😄

**Comment by webbertakken** [comment]
@digilifecz123 

I might be up for it. however given the context above, I'll need to look if I can make the time for it.

In the meantime anyone may feel free to pick this one up.

**Comment by tuanphungcz** [comment]
hey @webbertakken would you still be interested in rewriting it to TS? :)

**Comment by webbertakken** [comment]
> hey @webbertakken would you still be interested in rewriting it to TS? :)

Sorry I have a few other open source projects running at the moment that need a lot of attention. Don't count me out, but feel free to pick this up in the mean time.

**Comment by marekfeikus** [comment]
Done.
