### ISSUE TITLE
Problem in use The library with typescript

### ISSUE THREAD

**Issue by ABDERRAHMANE-OUALI** [useAnimations/react-useanimations#31]
Hi I using the react library version in my project( React + Typescript )
when I importing The icon it said that didn't find corresponding types, I want to ask if there a @types/Library for UseAnimation or anything else

**Comment by marekfeikus** [comment]
https://github.com/useAnimations/react-useanimations/blob/master/src/typings.d.ts Icon is JSON, there's no further need for typings. If your TS config does not respect this file, just add this definition right inside your project.
