### ISSUE TITLE
Configure when animation plays and does not play?

### ISSUE THREAD

**Issue by cbaron3** [useAnimations/react-useanimations#32]
Hi,

I have been reading through the docs and I was wondering if there is a way to stop an icon from playing an animation?

I want to use the skipBack and skipForward icons but have them only "clickable" once the user satifies some criteria. Currently, even if the criteria isn't met and the button isn't allowed to progress the page, the skipForward animation still plays.

As an example, in the below video I want to be able to prevent the skipForward button from animating.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18433286/94087682-68bbec00-fddc-11ea-8b8b-6e9ca26ff368.gif)

Thanks!

**Comment by marekfeikus** [comment]
@cbaron3 Nope, unfortunately not possible currently.
