### ISSUE TITLE
Uncaught TypeError: Cannot read property 'animationData' of undefined

### ISSUE THREAD

**Issue by younggg96** [useAnimations/react-useanimations#33]
I use it for my hooks.js and material-UI project but there is a problem that
![image](https://user-images.githubusercontent.com/42145357/96218708-4e94aa00-0f53-11eb-8802-0b16fb2d2c32.png)

**Comment by marekfeikus** [comment]
@younggg96 you're probably using v2 version. API has changed, you're calling it with wrong props.
