### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by klokie** [useAnimations/react-useanimations#34]
Hi, what would be required to get this to work with React Native?
thanks

**Comment by klokie** [comment]
Hmm… does that response mean "not possible", "not worth it", or "need more info" @marekfeikus ? :)
To me it doesn't look impossible, but of course the web-based aspects (HTML tags, standard CSS, Lottie web etc) would need to be moved into more abstract implementations.

**Comment by marekfeikus** [comment]
@klokie Nothing is impossible, but as you mentioned it'd probably require some more abstractions and ton of testing. Feel free to play with it. The PR that would be react-native ready would be welcomed :)
