### ISSUE TITLE
How to change icon color and styles?

### ISSUE THREAD

**Issue by ShubhamVerma1811** [useAnimations/react-useanimations#36]
I should be able to change icon colors.
The only thing I could change was strokeColor, not the filled icon color.
In image, the heart should be complete red.

![Screenshot_20210121-190358~2.jpg](https://user-images.githubusercontent.com/25576658/105357938-829afd80-5c1b-11eb-959f-dd63069e549c.jpg)

**Comment by ABDERRAHMANE-OUALI** [comment]
I was too looking for this solution too

**Comment by The-Adult-In-The-Room** [comment]
+1

**Comment by rodoneill** [comment]
add pathCss="fill:#FFC0CB;"
