### ISSUE TITLE
Issues with re-renders if props change

### ISSUE THREAD

**Issue by addisonschultz** [useAnimations/react-useanimations#37]
I'm running into an issue with the component not re-rendering when props are changed. 

I'm working in the context of Framer, and you can see an example of the file I'm working with here: https://framer.com/projects/Animation--yDs4zhmRIWvhkDBNN4Vj-7Eziv?node=Gaf1laFOb

You can duplicate this file to your own account in order to edit it, or I can give edit access to this document for better debugging. 

Framer works by adding Property Controls to components, which in turn pass new props to the component itself. This is working, and is verified through React's `useEffect`, and logs the correct values when a prop is changed from the control. This prop is also passed to the component, but does not cause a re-render as it should.

If you force the component to re-render (pressing CMD + Enter with the component selected), the correct props are then applied to the component, telling me that the props reached the component but it didn't render the new props

Any help diving into this would be appreciated! Let me know if I can provide any more context.

**Comment by marekfeikus** [comment]
Fixed by #44
