### ISSUE TITLE
Typescript error when importing elements

### ISSUE THREAD

**Issue by davidjentjens** [useAnimations/react-useanimations#39]
In many if not all declaration files, types are being imported like this:

`import type { AnimationEffect } from './constants';
`
This is giving me the following typescript error:

`TypeScript error in C:/Users/.../node_modules/react-useanimations/utils/getEvents.d.ts(1,13):      
'=' expected.  TS1005`

I don't know if this happens because of a version mismatch, but it generates errors in the building process. I fixed it locally by simply changing the syntax to the following.

`import { AnimationEffect } from './constants';
`
This is a really cool package and I thought it might be good for me to let the author know of some issues I had with it.

**Comment by marekfeikus** [comment]
@davidjentjens Thanks for the report - it's possible that the bundler you're using has not yet supported `import type` for TS - eg. this nextJS discussion https://github.com/vercel/next.js/issues/11909#issuecomment-706118174

Please let me know if after some updates this is still an issue, thanks.

**Comment by marekfeikus** [comment]
closing as it shouldn't be an issue.
