### ISSUE TITLE
Odd Behavior When onClick Handler Changes State

### ISSUE THREAD

**Issue by ApplePieGiraffe** [useAnimations/react-useanimations#41]
If I have a `<UseAnimations/>` component that has an `onClick` event listener that changes the state of something within the component it's in (using hooks), I have to click the `<UseAnimations/>` component twice for the reverse animation to play.

And if the `onClick` event listener changes the state of something in the parent component, the reverse animation of the `<UseAnimations/>` component won't play at all.

I'm kind of new to React, so IDK why this is happening and/or if it's a problem with UseAnimations.

**Comment by marekfeikus** [comment]
Fixed by #44
