### ISSUE TITLE
Not updating color on strokeColor change

### ISSUE THREAD

**Issue by marcelommss** [useAnimations/react-useanimations#42]
If you use a state variable on strokeColor, it does not update on state change.

```
const [strokeColor, setStrokeColor] = useState<string>('white');

<UseAnimations animation={Menu} 
    reverse={props.IsMenuOpenned}
    size={36}
    strokeColor={props.strokeColor}    
  />
```

**Comment by Nachoferra1894** [comment]
Hi marcelo, could you solve this issue by any chance?

**Comment by marcelommss** [comment]
No, updating strokeColor does not update the component.

AS in the example bellow, when I update the strokeColor variable to black, it still shows white.
![image](https://user-images.githubusercontent.com/20825407/125141197-b21ac500-e0ea-11eb-9565-2e8370fc5e8c.png)

**Comment by marcelommss** [comment]
As a workaround I put the UseAnimations inside a div ("Container") and then force the color of the path's stroke.
![image](https://user-images.githubusercontent.com/20825407/131234052-ba1fb794-a886-47a9-9c31-361b587f3df6.png)
