### ISSUE TITLE
Make the icon accept parent css color

### ISSUE THREAD

**Issue by nicatspark** [useAnimations/react-useanimations#5]
Hi
I propose you let the svg icons take the parent css color by using the css keyword `currentColor`. It can be set on the `stroke` or `fill` property (or both). It can even have a fallback if you use css custom variables. Made a codepen example here https://codepen.io/nicolashervy/pen/ZEEOqWw

**Comment by tuanphungcz** [comment]
Hi, thanks for a propose 👍 
Support for currentColor is now available in the latest version.

Commmit here: https://github.com/useAnimations/react-useanimations/commit/a967043be7eaba91d559274f37fa1f968df78ec3#diff-73642d587163f2eb4d72f0fa6ebfba02R8
