### ISSUE TITLE
Error for react 18

### ISSUE THREAD

**Issue by Maraszynko** [useAnimations/react-useanimations#59]
$ npm install -S react-useanimations
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: quarkandspark@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.9.0" from react-useanimations@2.0.8
npm ERR! node_modules/react-useanimations
npm ERR!   react-useanimations@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by CesarBenavides777** [comment]
@Maraszynko I would add a `--force` or `--legacy-peer-deps` at the end of the install command

**Comment by amirreza-dev** [comment]
It will install it but it wont work

**Comment by tuanphungcz** [comment]
The issue has been resolved with the inclusion of support for React 18 in this pull request: [PR](https://github.com/useAnimations/react-useanimations/pull/74). The latest use-animations package should now be working properly with react 18

Thank you guys for your patience and understanding 🙏
