### ISSUE TITLE
Need to update website

### ISSUE THREAD

**Issue by lymine1996** [useAnimations/react-useanimations#65]
Based on my personal experience, the [official website](https://react.useanimations.com/) for this package showed up on the top while I searched for a relevant React package to use. However, the syntax for this package on the homepage seems to be outdated. I couldn't figure out the solution until I checked out the GitHub repo. If possible, could someone update the code example on the website please? So that it clears the confusion for first-time users like me.

**Comment by tuanphungcz** [comment]
@lymine1996 Thank you for the feedback! I just resolved in this [PR](https://github.com/useAnimations/react.useanimations.com/commits/master) 🚀 

And congratz on your first opened issue 👍
