### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by tsujp** [useAnimations/react-useanimations#7]
The author is unresponsive to critical issues regarding basic functionality of the repo with no response to these issues, is this repo being maintained or has it been abandoned?

**Comment by zilahir** [comment]
@tsujp seems like it being abandoned. I am planning to fork it, and continue.

**Comment by tsujp** [comment]
@zilahir 

I'll happily contribute to something written in Hooks, and preferably also TypeScript. I had to abandon this due to the issues surrounding wrapping components with events, and sometimes `useAnimation` throwing `null` which caused a crash in both dev and prod which was.. annoying. My lack of knowledge of Class Component React meant I didn't have the time, nor really the patience, to bother fixing. I started React with Hooks.

**Comment by tuanphungcz** [comment]
Hey guys, I'm sorry, I was quite unavailable lately. I'm planning to dedicate it more time now and go through the issues. 

@tsujp @zilahir if you are guys still interested in contributing, then I'm happy to discuss it.

**Comment by zilahir** [comment]
@digilifecz123 yeahh! i am still interested, happy to contribute! :)

**Comment by tuanphungcz** [comment]
@zilahir haha alright then, lets do some hacking time this weekend.( Ill go through the issues, finally 😅)

**Comment by tuanphungcz** [comment]
closing this issue and moving it here: https://github.com/useAnimations/react-useanimations/issues/12
