### ISSUE TITLE
react-useanimations wont work on React 18

### ISSUE THREAD

**Issue by amirreza-dev** [useAnimations/react-useanimations#70]
Hi this is the error I've got
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: shopinx@1.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.9.0" from react-useanimations@2.0.8
npm ERR! node_modules/react-useanimations
npm ERR!   react-useanimations@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/amirreza/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/amirreza/.npm/_logs/2022-10-29T21_12_11_495Z-debug-0.log

And I added --force or --legacy-peer-deps at the end of instillation and installed but won't work!
Please update this library

**Comment by tuanphungcz** [comment]
The issue has been resolved with the inclusion of support for React 18 in this pull request: [PR](https://github.com/useAnimations/react-useanimations/pull/74). The latest use-animations package should now be working properly with react 18

Thank you guys for your patience and understanding 🙏
