### ISSUE TITLE
How to make the checkbox default to be checked.

### ISSUE THREAD

**Issue by nicatspark** [useAnimations/react-useanimations#8]
Is there a way to have the checkbox default to checked?

**Comment by tuanphungcz** [comment]
hm, good question, we dont have a support for it.

**Comment by smuralimohan** [comment]
I think it is pretty important feature. Could you please help add it? Also for the visibility icons, they should appear 'struck off' by default and then the eye should be seen when clicked.

Please help by adding the features. Thank you.

**Comment by marekfeikus** [comment]
@smuralimohan @nicatspark It's implemented in the new release. Provide additional `reverse: boolean` prop to the `UseAnimation` component. See the README for more info.
