### ISSUE TITLE
Feature enhancement

### ISSUE THREAD

**Issue by wizz-e** [useAnimations/react-useanimations#85]
The library is great and the animations are slick but i think if you could make it so that we can destructure the icons and call multiple icons from the same line instead of calling them individually would be really nice  also it would be nice if instead of using <useanimation /> any time you want to add an icon you could just call the icon name as a component just like react-icons or lucide react

**Comment by tuanphungcz** [comment]
hey  @wisdomsGit21 thanks for the suggestion, we will consider this change in the upcoming version! 👍
